//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerFinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechayHora { get; set; }
        public Nullable<int> NumeroHora { get; set; }
        public Nullable<decimal> ValorReserva { get; set; }
        public Nullable<decimal> ValorDescuento { get; set; }
    }


}
